### ISSUE TITLE
 API Key  not  linking the transaction to our website ?

### ISSUE THREAD

**Issue by fenix011** [MultiSafepay/PHP#10]
We have just 
- set up a sandbox using the 'Connect'  controller... 
- and then changed the _default_ (?) API Key in ../config/config.php by the API Key related to our website, as per MultiSafePay Control (WebPanel at 'testmerchant')

when making a test payment ... i'm receiving the confirmation like 'transaction has been processed'... (see attached file - log ) 
[connectComplete&transactionid=1488837948.txt](https://github.com/MultiSafepay/PHP/files/822781/connectComplete.transactionid.1488837948.txt)

Why is it not related to our website at all  (e.g.: amount was 10 € ... not 1000 €, name of the payer ... ) eventhough we configured its API Key ? What are we missing ?

**Comment by JonkRuud** [comment]
@jordila without looking into how you have set this up its hard to give a direct answer. I think it would be best if you create a technical support ticket at MultiSafepay by e-mailing to techsupport @ multisafepay.com explaining the problem. Our Tech department can then contact you and look into your issue.

**Comment by JonkRuud** [comment]
@jordila did you contact our techsupport department and got this one resolved?

**Comment by JonkRuud** [comment]
Closed because no update was received
