### ISSUE TITLE
Typo in MultiSafepay_API_Object_Gateways

### ISSUE THREAD

**Issue by RonJeremyR6** [MultiSafepay/PHP#2]
[Wrong]
$this->success = $result->succes;

[Correct]
$this->success = $result->success;

Else it gives this error:
Undefined property: stdClass::$succes

**Comment by KiwiJason** [comment]
@RonJeremyR6  Thanks for point this out.

**Comment by RonJeremyR6** [comment]
No problem, great Class by the way..
