### ISSUE TITLE
Composer autoload missing, client classname non-unique and no namespaces

### ISSUE THREAD

**Issue by gwigz** [MultiSafepay/PHP#6]
This project can be required using Composer.

Previously we worked around this issue writing our own autoloader for `MultiSafepay_API_*` class files.

`MultiSafepay_API_*` name prefixes were removed by dbff6da9a0ec75f7cff9fa8115888936089bfa5a, now the classname "Client" can conflict with others in a namespaced PHP environment.

There are no Composer autoloaders configured to help migrate this issue.

**Comment by petski** [comment]
Could you please also make a new release (2.0.1?) that includes this fix?

**Comment by JonkRuud** [comment]
Hello Petski, sorry didn't get to it earlier, we just added it. Thanks for your input.
